### ISSUE TITLE
希望能够自定义标题

### ISSUE THREAD

**Issue by NagiWang** [visiky/resume#38]
## 这个项目真的非常棒！

我在使用中发现下面两个问题：
- 在 **配置简历** 部分各个标题都是固定的，没办法自定义标题的名字，也没办法新增标题项。
 ![](https://s3.bmp.ovh/imgs/2022/01/b95e3a8806206862.png)
- 以 **工作经历** 为例，如果该部分为空，则仍会在简历中显示该标题。我认为应该内容为空时应当自动隐藏该标题，或者提供一个选项给用户选择是否隐藏。
 ![](https://s3.bmp.ovh/imgs/2022/01/1f52dbf040f35130.png)

**Comment by visiky** [comment]
嗯嗯 这个也考虑过. 我抽空加上

**Comment by NagiWang** [comment]
OMG！ 小姐姐效率也太高了吧！
