### ISSUE TITLE
wait perf points

### ISSUE THREAD

**Issue by bigbigDreamer** [visiky/resume#61]
简单记录下，可以优化的细节点：

- [x] 1. 区分`ts` `type` | `interface` 导入模式
    
- 参见：[传送门](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html)

```ts
// eg

import React from 'react';

import type { ReactNode } from 'react'
```

&nbsp;&nbsp;&nbsp;或者

- **typescript 4.5 以上版本支持**

```ts
// eg

import React, { type ReactNode } from 'react';
```

- [x] 2. 借助`husky`在`commit`时触发`format`，避免忘记`format`

**Comment by visiky** [comment]
参考这个，帮忙加一下 prettier 的PR：https://github.com/visiky/plot-performance/commit/d391c3f4bf8a49c8f32f89e4043b2b4c339ff3e8

**Comment by bigbigDreamer** [comment]
> 参考这个，帮忙加一下 prettier 的PR：[visiky/plot-performance@d391c3f](https://github.com/visiky/plot-performance/commit/d391c3f4bf8a49c8f32f89e4043b2b4c339ff3e8)

嗯嗯，晚点我跟一下

**Comment by bigbigDreamer** [comment]
Todo 1 --- >  #62

**Comment by bigbigDreamer** [comment]
Todo 2 ---> #63

**Comment by bigbigDreamer** [comment]
All done!
